server:
  port: 8893

eureka:
  #eueka 主机名
  instance:
    hostname: localhost
  client:
    #提供者和消费者的注册地址
    service-url:
      defaultZone: http://localhost:5060/eurekaServer/eureka/
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tyx765488261/lijinpeng.git/11
          search-paths: project-config
          username: tyx765488261
          password: ljp13875718300
  spring:
    application:
      name: config-server
